In [1]:
import pandas as pd

In [9]:
please=pd.read_csv('/Users/denisdunn/Downloads/Incident-level/MIDIP_4.01.csv')

In [23]:
please.columns.values

array(['DispNum3', 'IncidNum3', 'DispNum4', 'IncidNum4', 'StAbb', 'ccode',
       'StDay', 'StMon', 'StYear', 'EndDay', 'EndMon', 'EndYear',
       'InSide A', 'SideA', 'Fatality', 'FatalPre', 'Action', 'HostLev',
       'RevType1', 'RevType2', 'Version'], dtype=object)

In [30]:
please.head()

,DispNum3,IncidNum3,DispNum4,IncidNum4,StAbb,ccode,StDay,StMon,StYear,EndDay,...,EndYear,InSide A,SideA,Fatality,FatalPre,Action,HostLev,RevType1,RevType2,Version
0,3551,3551001,-9,-9,BEL,211,16,7,1992,16,...,1992,1,1,2,0,7,3,2,0,4.01
1,3551,3551001,-9,-9,CAN,20,16,7,1992,16,...,1992,1,1,2,0,7,3,2,0,4.01
2,3551,3551001,-9,-9,DEN,390,16,7,1992,16,...,1992,1,1,2,0,7,3,2,0,4.01
3,3551,3551001,-9,-9,FRN,220,16,7,1992,16,...,1992,1,1,2,0,7,3,2,0,4.01
4,3551,3551001,-9,-9,GMY,255,16,7,1992,16,...,1992,1,1,2,0,7,3,2,0,4.01

In [24]:
please['HostLev'].value_counts()

1    2754
4    2120
3    1865
2     420
5      20
0       6
Name: HostLev, dtype: int64

In [19]:
power=pd.read_csv("/Users/denisdunn/Downloads/NMC_5_0/NMC_5_0.csv")

In [32]:
total=pd.merge(please,power,how='left',left_on=['StAbb','StYear'],right_on=['stateabb','year'])

In [72]:
total.describe()

,DispNum3,IncidNum3,DispNum4,IncidNum4,ccode_x,StDay,StMon,StYear,EndDay,EndMon,...,ccode_y,year,milex,milper,irst,pec,tpop,upop,cinc,version
count,7185.000000,7.185000e+03,7185.000000,7.185000e+03,7185.000000,7185.000000,7185.000000,7185.000000,7185.000000,7185.000000,...,7168.000000,7168.000000,7.168000e+03,7168.000000,7168.000000,7.168000e+03,7.168000e+03,7168.000000,7.168000e+03,7168.0
mean,4233.386917,4.233438e+06,23047.182185,2.305161e+07,518.140014,14.703549,6.290745,1999.945024,14.054976,6.336952,...,517.688058,1999.955636,2.928746e+07,436.303292,18032.078823,3.686564e+05,1.138581e+05,31744.394392,2.217873e-02,2011.0
std,218.275091,2.182679e+05,26017.853098,2.601401e+07,231.777060,10.023390,3.466304,4.850971,11.060318,3.462197,...,231.674212,4.850692,8.805007e+07,557.701765,46860.545559,8.221313e+05,2.656740e+05,71011.051814,4.149635e-02,0.0
min,3551.000000,3.551001e+06,-9.000000,-9.000000e+00,2.000000,-9.000000,1.000000,1992.000000,-9.000000,1.000000,...,2.000000,1992.000000,-9.000000e+00,-9.000000,0.000000,1.500000e+01,1.900000e+01,0.000000,6.900000e-07,2011.0
25%,4137.000000,4.137024e+06,-9.000000,-9.000000e+00,352.000000,8.000000,3.000000,1996.000000,7.000000,3.000000,...,352.000000,1996.000000,4.940000e+05,58.000000,0.000000,1.020700e+04,5.836000e+03,1990.000000,1.333700e-03,2011.0
50%,4212.000000,4.212001e+06,10305.000000,1.030500e+07,640.000000,15.000000,6.000000,1999.000000,15.000000,6.000000,...,640.000000,1999.000000,2.687000e+06,185.000000,300.000000,3.630000e+04,2.213200e+04,5510.000000,4.521600e-03,2011.0
75%,4375.000000,4.375002e+06,50201.000000,5.020135e+07,698.000000,23.000000,9.000000,2003.000000,23.000000,9.000000,...,696.000000,2003.000000,1.132100e+07,619.000000,14475.000000,1.771680e+05,6.836500e+04,26920.000000,1.518030e-02,2011.0
max,4599.000000,4.599002e+06,71002.000000,7.100200e+07,986.000000,31.000000,12.000000,2010.000000,31.000000,12.000000,...,986.000000,2010.000000,6.936000e+08,3030.000000,638743.000000,4.529730e+06,1.359821e+06,612933.000000,2.081897e-01,2011.0

In [111]:
total.columns.values

array(['DispNum3', 'IncidNum3', 'DispNum4', 'IncidNum4', 'StAbb',
       'ccode_x', 'StDay', 'StMon', 'StYear', 'EndDay', 'EndMon',
       'EndYear', 'InSide A', 'SideA', 'Fatality', 'FatalPre', 'Action',
       'HostLev', 'RevType1', 'RevType2', 'Version', 'stateabb',
       'ccode_y', 'year', 'milex', 'milper', 'irst', 'pec', 'tpop',
       'upop', 'cinc', 'version'], dtype=object)

In [53]:
dip=pd.read_csv('/Users/denisdunn/Downloads/Diplomatic_Exchange_2006.1/Diplomatic_Exchange_2006v1.csv')

In [62]:
dip.head()

   ccode1  ccode2  year  DR_at_1  DR_at_2  DE      version
0       2      20  1920        0        0   0  2006.099976
1       2      20  1925        0        0   0  2006.099976
2       2      20  1930        0        2   1  2006.099976
3       2      20  1935        2        2   1  2006.099976
4       2      20  1940        2        2   1  2006.099976

In [110]:
usdip=dip[dip['ccode1']==2]

In [129]:
usdips=usdip[dip['year']>1991]

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [131]:
usdiplomat=usdips[['ccode2','year','DE']]

In [109]:
codes=pd.read_csv('/Users/denisdunn/Downloads/COW country codes.csv')

In [151]:
codes[codes['StateNme']=='Russia']

    StateAbb  CCode StateNme
101      RUS    365   Russia

In [77]:
alliance=pd.read_csv('/Users/denisdunn/Downloads/version4.1_csv/alliance_v4.1_by_dyad_yearly.csv')

In [78]:
alliance.describe()

,version4id,ccode1,ccode2,dyad_st_day,dyad_st_month,dyad_st_year,dyad_end_day,dyad_end_month,dyad_end_year,left_censor,right_censor,defense,neutrality,nonaggression,entente,year,version
count,74129.000000,74129.000000,74129.000000,74129.000000,74129.000000,74129.000000,16354.000000,16354.000000,74129.000000,74129.000000,74129.000000,74129.000000,74129.000000,74108.000000,74117.000000,74129.000000,7.412900e+04
mean,221.464069,282.650272,361.628769,13.668092,6.292315,1958.721566,17.339489,5.802434,1998.030879,0.017497,0.779385,0.768714,0.024808,0.745480,0.836731,1977.041239,4.100000e+00
std,69.167418,233.254479,242.795033,9.354374,3.589628,32.011897,8.725122,3.194013,34.121950,0.131113,0.414664,0.421658,0.155541,0.435594,0.369613,59.362657,3.428392e-13
min,1.000000,2.000000,20.000000,1.000000,1.000000,1816.000000,1.000000,1.000000,1820.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.100000e+00
25%,210.000000,60.000000,140.000000,4.000000,3.000000,1947.000000,10.000000,3.000000,2012.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1967.000000,4.100000e+00
50%,210.000000,212.000000,325.000000,13.000000,5.000000,1961.000000,20.000000,5.000000,2012.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1986.000000,4.100000e+00
75%,230.000000,482.000000,645.000000,22.000000,9.000000,1981.000000,23.000000,8.000000,2012.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,2000.000000,4.100000e+00
max,414.000000,900.000000,920.000000,31.000000,12.000000,2012.000000,31.000000,12.000000,2012.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2012.000000,4.100000e+00

In [79]:
usallies=alliance[alliance['ccode1']==2]

In [91]:
us=usallies[usallies['year']>1991]

In [96]:
uspact=us[(us['defense'] ==1) | (us['neutrality'] ==1) |(us['nonaggression']==1)]

In [155]:
rus=alliance[alliance['ccode1']==365]

In [165]:
ruse=rus[rus['year']>1991]

In [167]:
ruspact=ruse[(ruse['defense'] ==1) | (ruse['neutrality'] ==1) |(ruse['nonaggression']==1)]

In [168]:
ruspact['Allies']=1

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [170]:
ruspact=ruspact[['ccode2','year','Allies']]

In [172]:
ruspact

       ccode2  year  Allies
62402     731  1992       1
62403     731  1993       1
62404     731  1994       1
62405     731  1995       1
69008     375  1992       1
69009     375  1993       1
69010     375  1994       1
69011     375  1995       1
69012     375  1996       1
69013     375  1997       1
69014     375  1998       1
69015     375  1999       1
69016     375  2000       1
69017     375  2001       1
69018     375  2002       1
69019     375  2003       1
69020     375  2004       1
69021     375  2005       1
69022     375  2006       1
69023     375  2007       1
69024     375  2008       1
69025     375  2009       1
69026     375  2010       1
69027     375  2011       1
69028     375  2012       1
69290     369  1995       1
69291     369  1996       1
69292     369  1997       1
69293     369  1998       1
69294     369  1999       1
...       ...   ...     ...
73411     701  2003       1
73412     701  2004       1
73413     701  2005       1
73414     701  2006       1
73415     701  2007       1
73416     701  2008       1
73417     701  2009       1
73418     701  2010       1
73419     701  2011       1
73420     701  2012       1
73652     372  2004       1
73653     372  2005       1
73654     372  2006       1
73655     372  2007       1
73656     372  2008       1
73665     704  2005       1
73666     704  2006       1
73667     704  2007       1
73668     704  2008       1
73669     704  2009       1
73670     704  2010       1
73671     704  2011       1
73672     704  2012       1
74076     370  2009       1
74077     370  2010       1
74078     370  2011       1
74079     370  2012       1
74080     371  2010       1
74081     371  2011       1
74082     371  2012       1

[628 rows x 3 columns]

In [122]:
usally=uspact[['ccode2','year','right_censor']]

In [105]:
impts=pd.read_csv("/Users/denisdunn/Downloads/National_COW_4.0.csv")

In [107]:
trade=impts[impts['year']>1991]

In [108]:
trade=trade[['ccode','stateabb','year','imports','exports']]

In [123]:
tottrade=pd.merge(total,trade,how='left',left_on=['ccode_x','year'],right_on=['ccode','year'])

In [124]:
tottrade.head()

,DispNum3,IncidNum3,DispNum4,IncidNum4,StAbb,ccode_x,StDay,StMon,StYear,EndDay,...,irst,pec,tpop,upop,cinc,version,ccode,stateabb_y,imports,exports
0,3551,3551001,-9,-9,BEL,211,16,7,1992,16,...,10332.0,78228.0,10055.0,1460.0,0.005132,2011.0,211.0,BEL,117052.000000,115782.500000
1,3551,3551001,-9,-9,CAN,20,16,7,1992,16,...,13924.0,288704.0,28377.0,10686.0,0.012017,2011.0,20.0,CAN,137327.947656,133447.209611
2,3551,3551001,-9,-9,DEN,390,16,7,1992,16,...,591.0,31374.0,5170.0,1220.0,0.001657,2011.0,390.0,DEN,35216.617533,41138.761683
3,3551,3551001,-9,-9,FRN,220,16,7,1992,16,...,18024.0,242844.0,57374.0,9986.0,0.021659,2011.0,220.0,FRN,241299.771364,235241.771755
4,3551,3551001,-9,-9,GMY,255,16,7,1992,16,...,39711.0,480287.0,80570.0,25928.0,0.031551,2011.0,255.0,GMY,403878.810700,425304.733414

In [126]:
work=pd.merge(tottrade,usally,how='left',left_on=['ccode_x','year'],right_on=['ccode2','year'])

In [133]:
ustot=pd.merge(work,usdiplomat,how='left',left_on=['ccode_x','year'],right_on=['ccode2','year'])

In [135]:
ustot.columns.values

array(['DispNum3', 'IncidNum3', 'DispNum4', 'IncidNum4', 'StAbb',
       'ccode_x', 'StDay', 'StMon', 'StYear', 'EndDay', 'EndMon',
       'EndYear', 'InSide A', 'SideA', 'Fatality', 'FatalPre', 'Action',
       'HostLev', 'RevType1', 'RevType2', 'Version', 'stateabb_x',
       'ccode_y', 'year', 'milex', 'milper', 'irst', 'pec', 'tpop',
       'upop', 'cinc', 'version', 'ccode', 'stateabb_y', 'imports',
       'exports', 'ccode2_x', 'right_censor', 'ccode2_y', 'DE'],
      dtype=object)

In [142]:
ustot=ustot[['StAbb','ccode_x','InSide A', 'SideA', 'Fatality', 'FatalPre', 'Action',
       'HostLev', 'year', 'milex', 'milper', 'irst', 'pec', 'tpop',
       'upop', 'cinc', 'imports',
       'exports', 'right_censor', 'DE']]

In [171]:
pd.merge(ustot,ruspact,how='left',left_on=['ccode_x','year'],right_on=['ccode2','year'])

,StAbb,ccode_x,InSide A,SideA,Fatality,FatalPre,Action,HostLev,year,milex,...,pec,tpop,upop,cinc,imports,exports,right_censor,DE,ccode2,Allies
0,BEL,211,1,1,2,0,7,3,1992.0,3160000.0,...,78228.0,10055.0,1460.0,0.005132,1.170520e+05,1.157825e+05,1.0,NaN,NaN,NaN
1,CAN,20,1,1,2,0,7,3,1992.0,10310000.0,...,288704.0,28377.0,10686.0,0.012017,1.373279e+05,1.334472e+05,1.0,NaN,NaN,NaN
2,CAN,20,1,1,2,0,7,3,1992.0,10310000.0,...,288704.0,28377.0,10686.0,0.012017,1.373279e+05,1.334472e+05,1.0,NaN,NaN,NaN
3,CAN,20,1,1,2,0,7,3,1992.0,10310000.0,...,288704.0,28377.0,10686.0,0.012017,1.373279e+05,1.334472e+05,1.0,NaN,NaN,NaN
4,DEN,390,1,1,2,0,7,3,1992.0,2790000.0,...,31374.0,5170.0,1220.0,0.001657,3.521662e+04,4.113876e+04,1.0,NaN,NaN,NaN
5,FRN,220,1,1,2,0,7,3,1992.0,34870000.0,...,242844.0,57374.0,9986.0,0.021659,2.412998e+05,2.352418e+05,1.0,NaN,NaN,NaN
6,GMY,255,1,1,2,0,7,3,1992.0,33380000.0,...,480287.0,80570.0,25928.0,0.031551,4.038788e+05,4.253047e+05,1.0,NaN,NaN,NaN
7,GRC,350,1,1,2,0,7,3,1992.0,4400000.0,...,48110.0,10322.0,2071.0,0.003782,2.281802e+04,9.437492e+03,1.0,NaN,NaN,NaN
8,ITA,325,1,1,2,0,7,3,1992.0,19890000.0,...,229778.0,56859.0,14366.0,0.019859,1.867298e+05,1.774280e+05,1.0,NaN,NaN,NaN
9,NTH,210,1,1,2,0,7,3,1992.0,8010000.0,...,159307.0,15184.0,4137.0,0.006672,1.298131e+05,1.386206e+05,1.0,NaN,NaN,NaN
10,POR,235,1,1,2,0,7,3,1992.0,1660000.0,...,26167.0,9867.0,1148.0,0.001865,3.073903e+04,1.880100e+04,1.0,NaN,NaN,NaN
11,SPN,230,1,1,2,0,7,3,1992.0,7680000.0,...,146194.0,39008.0,15951.0,0.011006,9.983310e+04,6.402225e+04,1.0,NaN,NaN,NaN
12,TUR,640,1,1,2,0,7,3,1992.0,4140000.0,...,83606.0,58401.0,21984.0,0.013638,2.437260e+04,1.459588e+04,1.0,NaN,640.0,1.0
13,TUR,640,1,1,2,0,7,3,1992.0,4140000.0,...,83606.0,58401.0,21984.0,0.013638,2.437260e+04,1.459588e+04,1.0,NaN,640.0,1.0
14,UKG,200,1,1,2,0,7,3,1992.0,42330000.0,...,341540.0,58006.0,47761.0,0.027372,2.215568e+05,1.900112e+05,1.0,NaN,NaN,NaN
15,USA,2,1,1,2,0,7,3,1992.0,286892000.0,...,2856725.0,255391.0,65413.0,0.148314,5.526133e+05,4.473859e+05,NaN,NaN,NaN,NaN
16,YUG,345,0,0,2,0,0,1,1992.0,1300000.0,...,26253.0,10448.0,2381.0,0.002331,1.246739e+04,1.084120e+04,NaN,NaN,NaN,NaN
17,BEL,211,1,1,2,0,13,4,1993.0,4000000.0,...,76038.0,10084.0,1466.0,0.005184,1.063780e+05,1.136049e+05,1.0,NaN,NaN,NaN
18,FRN,220,1,1,2,0,13,4,1993.0,37200000.0,...,244071.0,57654.0,10053.0,0.021995,2.025383e+05,2.157160e+05,1.0,NaN,NaN,NaN
19,GMY,255,1,1,2,0,13,4,1993.0,36700000.0,...,475727.0,81187.0,25968.0,0.031423,3.297836e+05,3.642593e+05,1.0,NaN,NaN,NaN
20,YUG,345,0,0,2,0,0,1,1993.0,-9.0,...,23418.0,10482.0,2809.0,0.002033,NaN,NaN,NaN,NaN,NaN,NaN
21,GRC,350,1,1,2,0,13,4,1993.0,3861000.0,...,44812.0,10379.0,2069.0,0.003721,2.020035e+04,9.092874e+03,1.0,NaN,NaN,NaN
22,ITA,325,1,1,2,0,13,4,1993.0,20570000.0,...,230789.0,57049.0,14204.0,0.020147,1.475972e+05,1.682769e+05,1.0,NaN,NaN,NaN
23,NTH,210,1,1,2,0,13,4,1993.0,7356000.0,...,162790.0,15290.0,4354.0,0.006698,1.132752e+05,1.282303e+05,1.0,NaN,NaN,NaN
24,SPN,230,1,1,2,0,13,4,1993.0,7700000.0,...,139383.0,39086.0,15581.0,0.010982,8.185909e+04,6.270060e+04,1.0,NaN,NaN,NaN
25,UKG,200,1,1,2,0,13,4,1993.0,34020000.0,...,346078.0,58191.0,48842.0,0.025529,2.053859e+05,1.801865e+05,1.0,NaN,NaN,NaN
26,USA,2,1,1,2,0,13,4,1993.0,297600000.0,...,2921265.0,258132.0,66072.0,0.153516,6.030091e+05,4.659434e+05,NaN,NaN,NaN,NaN
27,YUG,345,0,0,0,0,0,1,1993.0,-9.0,...,23418.0,10482.0,2809.0,0.002033,NaN,NaN,NaN,NaN,NaN,NaN
28,FRN,220,1,1,0,0,7,3,1993.0,37200000.0,...,244071.0,57654.0,10053.0,0.021995,2.025383e+05,2.157160e+05,1.0,NaN,NaN,NaN
29,UKG,200,1,1,0,0,7,3,1993.0,34020000.0,...,346078.0,58191.0,48842.0,0.025529,2.053859e+05,1.801865e+05,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8168,IND,750,1,1,0,0,14,4,2010.0,30865000.0,...,1232691.0,1205625.0,209511.0,0.079472,3.507828e+05,2.229216e+05,NaN,NaN,NaN,NaN
8169,BNG,771,0,0,0,0,0,1,2010.0,1237000.0,...,44895.0,151125.0,23154.0,0.007411,2.781285e+04,1.649695e+04,NaN,NaN,NaN,NaN
8170,IND,750,1,1,1,-9,17,4,2010.0,30865000.0,...,1232691.0,1205625.0,209511.0,0.079472,3.507828e+05,2.229216e+05,NaN,NaN,NaN,NaN
8171,BNG,771,0,0,1,-9,17,4,2010.0,1237000.0,...,44895.0,151125.0,23154.0,0.007411,2.781285e+04,1.649695e+04,NaN,NaN,NaN,NaN
8172,BNG,771,1,0,0,0,16,4,2010.0,1237000.0,...,44895.0,151125.0,23154.0,0.007411,2.781285e+04,1.649695e+04,NaN,NaN,NaN,NaN
8173,IND,750,0,1,0,0,0,1,2010.0,30865000.0,...,1232691.0,1205625.0,209511.0,0.079472,3.507828e+05,2.229216e+05,NaN,NaN,NaN,NaN
8174,IRN,630,1,1,1,1,17,4,2009.0,8636000.0,...,364612.0,73543.0,26184.0,0.014039,4.974050e+04,7.439484e+04,NaN,NaN,NaN,NaN
8175,AFG,700,0,0,0,0,17,4,2009.0,252000.0,...,1414.0,27708.0,3933.0,0.001494,6.947939e+03,4.458751e+02,NaN,NaN,NaN,NaN
8176,MYA,775,1,1,0,0,16,4,2009.0,-9.0,...,20407.0,51540.0,7409.0,0.006478,7.080934e+03,5.912684e+03,NaN,NaN,NaN,NaN
8177,THI,800,0,0,0,0,0,1,2009.0,4732000.0,...,195374.0,66277.0,10074.0,0.007768,1.347344e+05,1.519103e+05,NaN,NaN,NaN,NaN
8178,MYA,775,1,1,0,0,11,3,2009.0,-9.0,...,20407.0,51540.0,7409.0,0.006478,7.080934e+03,5.912684e+03,NaN,NaN,NaN,NaN
8179,BNG,771,0,0,0,0,0,1,2009.0,1016000.0,...,40839.0,149503.0,22475.0,0.007388,2.185371e+04,1.437748e+04,NaN,NaN,NaN,NaN
8180,MYA,775,1,1,0,0,7,3,2009.0,-9.0,...,20407.0,51540.0,7409.0,0.006478,7.080934e+03,5.912684e+03,NaN,NaN,NaN,NaN
8181,BNG,771,0,0,0,0,0,1,2009.0,1016000.0,...,40839.0,149503.0,22475.0,0.007388,2.185371e+04,1.437748e+04,NaN,NaN,NaN,NaN
8182,BNG,771,1,0,0,0,11,3,2009.0,1016000.0,...,40839.0,149503.0,22475.0,0.007388,2.185371e+04,1.437748e+04,NaN,NaN,NaN,NaN
8183,MYA,775,0,1,0,0,0,1,2009.0,-9.0,...,20407.0,51540.0,7409.0,0.006478,7.080934e+03,5.912684e+03,NaN,NaN,NaN,NaN
8184,MYA,775,1,1,0,0,11,3,2009.0,-9.0,...,20407.0,51540.0,7409.0,0.006478,7.080934e+03,5.912684e+03,NaN,NaN,NaN,NaN
8185,BNG,771,0,0,0,0,0,1,2009.0,1016000.0,...,40839.0,149503.0,22475.0,0.007388,2.185371e+04,1.437748e+04,NaN,NaN,NaN,NaN
8186,IRN,630,1,1,0,0,11,3,2009.0,8636000.0,...,364612.0,73543.0,26184.0,0.014039,4.974050e+04,7.439484e+04,NaN,NaN,NaN,NaN
8187,PAK,770,0,0,0,0,0,1,2009.0,3811000.0,...,93237.0,170094.0,38910.0,0.013952,3.164763e+04,1.752315e+04,1.0,NaN,NaN,NaN
8188,USA,2,1,1,0,0,16,4,2010.0,693600000.0,...,3211935.0,312247.0,177349.0,0.148098,1.968115e+06,1.277486e+06,NaN,NaN,NaN,NaN
8189,PAK,770,0,0,0,0,0,1,2010.0,5599000.0,...,92562.0,173149.0,40238.0,0.014059,4.357041e+04,2.127917e+04,1.0,NaN,NaN,NaN
8190,USA,2,1,1,0,0,17,4,2010.0,693600000.0,...,3211935.0,312247.0,177349.0,0.148098,1.968115e+06,1.277486e+06,NaN,NaN,NaN,NaN
8191,PAK,770,0,0,1,3,17,4,2010.0,5599000.0,...,92562.0,173149.0,40238.0,0.014059,4.357041e+04,2.127917e+04,1.0,NaN,NaN,NaN
8192,USA,2,1,1,0,0,16,4,2010.0,693600000.0,...,3211935.0,312247.0,177349.0,0.148098,1.968115e+06,1.277486e+06,NaN,NaN,NaN,NaN
8193,PAK,770,0,0,0,0,0,1,2010.0,5599000.0,...,92562.0,173149.0,40238.0,0.014059,4.357041e+04,2.127917e+04,1.0,NaN,NaN,NaN
8194,IRN,630,1,1,0,0,15,4,2010.0,10564000.0,...,375116.0,74462.0,26666.0,0.014001,6.639507e+04,9.869300e+04,NaN,NaN,NaN,NaN
8195,AFG,700,0,0,0,0,0,1,2010.0,277000.0,...,1765.0,28398.0,4102.0,0.001836,8.651437e+03,5.005202e+02,NaN,NaN,NaN,NaN
8196,AFG,700,1,0,0,0,15,4,2010.0,277000.0,...,1765.0,28398.0,4102.0,0.001836,8.651437e+03,5.005202e+02,NaN,NaN,NaN,NaN
8197,IRN,630,0,1,0,0,0,1,2010.0,10564000.0,...,375116.0,74462.0,26666.0,0.014001,6.639507e+04,9.869300e+04,NaN,NaN,NaN,NaN